### ISSUE TITLE
RuntimeError: Builds without cython

### ISSUE THREAD

**Issue by syazw** [r9y9/nnmnkwii#49]
![run](https://user-images.githubusercontent.com/32951997/31937172-3a4ad194-b8e6-11e7-9232-06030cfa7b94.png)

Hi @r9y9 , I run python setup.py develop , but it still give me this error.
I hope u can help me to fix this error. Thank you.

**Comment by r9y9** [comment]
Please install cython before installation.

```
pip install cython
```

**Comment by r9y9** [comment]
By the way, I will try to fix builds without cython in the next release.

**Comment by syazw** [comment]
okay thank you @r9y9

**Comment by r9y9** [comment]
New pypi release v0.0.8 https://pypi.python.org/pypi/nnmnkwii should fix this. Please reopen if you still have this issue.
