### ISSUE TITLE
Demonstration (tutorial) notebooks

### ISSUE THREAD

**Issue by r9y9** [r9y9/nnmnkwii#5]
TODO list:

Voice conversion (VC), Text-to-speech (TTS)

https://github.com/r9y9/nnmnkwii_gallery

English:

- [x] GMM VC (en)
- [x] DNN VC (en) (I have this locally): https://github.com/r9y9/gantts
- [x] DNN TTS (en) #2 
- [x] LSTM-RNN TTS (en)
- [x] End-to-end TTS (en) #3 

Japanese:

- ~~GMM VC (jp) (I have this locally)~~
- ~~DNN VC (jp) (I have this locally)~~
- [x] DNN TTS (jp)  (i have this locally) https://github.com/r9y9/gantts/tree/jp
- [x] End-to-end TTS https://github.com/r9y9/deepvoice3_pytorch

**Comment by r9y9** [comment]
https://github.com/r9y9/nnmnkwii_gallery/commit/01c71e0f0748c7d792991e58698bdd7d5c292561 Japanese TTS demos

**Comment by HarmanGhawaddi** [comment]
> TODO list:
> 
> Voice conversion (VC), Text-to-speech (TTS)
> 
> https://github.com/r9y9/nnmnkwii_gallery
> 
> English:
> 
> * [x]  GMM VC (en)
> * [x]  DNN VC (en) (I have this locally): https://github.com/r9y9/gantts
> * [x]  DNN TTS (en) #2
> * [x]  LSTM-RNN TTS (en)
> * [x]  End-to-end TTS (en) #3
> 
> Japanese:
> 
> * [ ]  GMM VC (jp) (I have this locally)
> * [ ]  DNN VC (jp) (I have this locally)
> * [x]  DNN TTS (jp)  (i have this locally) https://github.com/r9y9/gantts/tree/jp
> * [x]  End-to-end TTS https://github.com/r9y9/deepvoice3_pytorch

Can i play these tts locally on my window os that has no NVIDIA GPU .
