### ISSUE TITLE
Data files cannot be fetched.

### ISSUE THREAD

**Issue by KORGUCHI** [r9y9/nnmnkwii#65]
I tried the 00-Quick start guide and got the following warning in [12].

```
/home/korguchi/anaconda3/lib/python3.6/site-packages/nnmnkwii/datasets/__init__.py:125: UserWarning: No files are collected. You might have specified wrong data source.
  warn("No files are collected. You might have specified wrong data source.")
```
I also tried the example of nnmnkwii.datasets.FileSourceDataset. The same problem occured.

Environment
-  Ubuntu 16.04.3 LTS (Windows Subsystem for Linux) 
-  Anaconda3 Python3.6

**Comment by r9y9** [comment]
Hi, thank you for the report. Is this reproducible with the current master? There was a bug https://github.com/r9y9/nnmnkwii/commit/177b12cef42d4a9ddeebc4ee14f23c7ce7c54487 that example data was not included in the pypi release and I am wondering if you are hitting the bug or not.

**Comment by KORGUCHI** [comment]
Thank you for your reply.
As you mentioned, I updated to the latest version but It still gives that warning...

**Comment by r9y9** [comment]
Okay, can you please share the notebook? I cannot reproduce locally.

**Comment by KORGUCHI** [comment]
I ran the 00-Quick start guide.ipynb in nnmnkwii-gallery as it is.
I suspect it is the unique problem to my environment.

**Comment by r9y9** [comment]
Sorry, I mean, can you upload the notebook to https://gist.github.com/ (or whatever you want)? Your notebook contains cell outputs and warnings. It helps me to identify what cell(s) of the notebook was going wrong. Running the 00-Quick start guide.ipynb in my environment does not produce the warning you mentioned.

**Comment by KORGUCHI** [comment]
I'm the one who should be sorry.
This is the notebook.
https://gist.github.com/KORGUCHI/2379fa5ba4e1a878152b37c791a9ad25

**Comment by r9y9** [comment]
Thank you very much! I am now able to reproduce. I'm looking into it.

**Comment by r9y9** [comment]
I think I fixed the issue. Could you check if it works with the latest master?

```
pip install git+https://github.com/r9y9/nnmnkwii
```

**Comment by KORGUCHI** [comment]
It completely works! I would really appreciate your quick reply and great works.

**Comment by r9y9** [comment]
:+1: 

Let me know if you have another problem.
