### ISSUE TITLE
installation error on python3.5 ubuntu 14.04

### ISSUE THREAD

**Issue by lightsailpro** [r9y9/nnmnkwii#69]
I install using: python3.5 -m pip -v --no-cache-dir install nnmnkwii, and got the following error. Plewase advise how to resolve this.
......................
    error: can't copy 'nnmnkwii/util/_example_data/slt_arctic_demo_data': doesn't exist or not a regular file
error
Cleaning up...
  Removing source in /tmp/pip-build-vrm0moli/nnmnkwii
Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vrm0moli/nnmnkwii/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0tw90rj7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vrm0moli/nnmnkwii/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vrm0moli/nnmnkwii/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0tw90rj7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vrm0moli/nnmnkwii/

**Comment by r9y9** [comment]
Sorry for the inconvenience. Does the following work for you?

```
pip install git+https://github.com/r9y9/nnmnkwii
```

**Comment by lightsailpro** [comment]
Yes, it worked. Thanks a lot.

**Comment by r9y9** [comment]
Okay, thank you. I will prepare a new release.

**Comment by r9y9** [comment]
Fixed at https://github.com/r9y9/nnmnkwii/releases/tag/v0.0.13
