### ISSUE TITLE
numpy is a dependency, but it is also required by setup, thus a "cold" pip install nnmnkwii fails

### ISSUE THREAD

**Issue by Martin-Laclaustra** [r9y9/nnmnkwii#80]
This could be related to https://github.com/r9y9/nnmnkwii/issues/64 .
Installing with `pip install nnmnkwii` as instructed in the main readme fails when done in a new environment.
Performing `pip install numpy` before, and then `pip install nnmnkwii` succeeds.
This is because in setup.py numpy is imported in
https://github.com/r9y9/nnmnkwii/blob/3162967f8a40bb33a1556c513e682d5e8a84dc4c/setup.py#L12
because it is used in
https://github.com/r9y9/nnmnkwii/blob/3162967f8a40bb33a1556c513e682d5e8a84dc4c/setup.py#L83
and
https://github.com/r9y9/nnmnkwii/blob/3162967f8a40bb33a1556c513e682d5e8a84dc4c/setup.py#L90
It would be preferable if these actions could be performed differently.
Numpy is actually a dependency of the package, but it is not granted to be installed before the actual dependencies file (setup.py) is executed.
https://github.com/r9y9/nnmnkwii/blob/3162967f8a40bb33a1556c513e682d5e8a84dc4c/setup.py#L126
Regards.

**Comment by r9y9** [comment]
If https://github.com/r9y9/pysptk/issues/65 gets fixed, I will do the same for the nnmnkwii and tag a new release.
