### ISSUE TITLE
Documentation for nnmnkwii.io.hts is out of date

### ISSUE THREAD

**Issue by korguchi** [r9y9/nnmnkwii#89]
It seems the documentation for nnmnkwii.io.hts is not up to date.
https://r9y9.github.io/nnmnkwii/v0.0.1/_modules/nnmnkwii/io/hts.html

For example, according to the source in this doc,  it needs to change member variables of labels to change frame_shift_in_micro_sec. however, in the latest version, it is provided as an argument of each class method.
https://github.com/r9y9/nnmnkwii/blob/master/nnmnkwii/io/hts.py

**Comment by r9y9** [comment]
I guess you are seeing the old version of docs. Please check out the latest doc at https://r9y9.github.io/nnmnkwii/latest/. 

As far as I can tell, I have been updating the docs for every release. You can find the docs for all versions at https://github.com/r9y9/nnmnkwii/tree/gh-pages.

**Comment by korguchi** [comment]
Oh, as you said, I hit an older doc on Google search.
I'm so sorry and thank you for your time.

**Comment by r9y9** [comment]
I'm closing the issue.
