### ISSUE TITLE
Support JVS as Dataset

### ISSUE THREAD

**Issue by Aria-K-Alethia** [r9y9/nnmnkwii#91]
Hi,

I wonder if you want to add [JVS](https://sites.google.com/site/shinnosuketakamichi/research-topics/jvs_corpus) as a dataset, it is a Japanese Multi-speaker speech dataset.

If you want, I think I can write the code.

**Comment by r9y9** [comment]
That would be great to have. Do you mind making a PR?

**Comment by Aria-K-Alethia** [comment]
> That would be great to have. Do you mind making a PR?

OK, no problem.

**Comment by Aria-K-Alethia** [comment]
Have you see the PR ? I committed the code, but seems can not pass the testcode, I don't know the reason...

**Comment by r9y9** [comment]
Sorry! I’ve been busy for a while. I’ll take a look once I get some time.

**Comment by Aria-K-Alethia** [comment]
Hi, I've fixed some of the inappropriate codes your mentioned, see it if you have time.

**Comment by Aria-K-Alethia** [comment]
The code has been modified, however I don't know why the CI test failed again.

**Comment by r9y9** [comment]
CI failure doesn't seem to be related to your changes. Let me see if it still persists after merging the PR.

**Comment by r9y9** [comment]
note to self: better to update docs and changelogs as well. After that, I will close the issue.

**Comment by r9y9** [comment]
CI failure seems related to https://github.com/nedbat/coveragepy/issues/916
