### ISSUE TITLE
How to reproduce lab files for jsut?

### ISSUE THREAD

**Issue by thrfdth** [r9y9/nnmnkwii#97]
Thank you for great repo! I'm working on vocoder training with jsut and I tried reproduction of lab files but after running 
`perl ./segment_julius.pl jsut/`
I've got lab files which are pretty different style than them downloaded in colab.
I'm planning to train a vocoder with own dataset and i prefer same kind of lab files as ones from colab because i've managed to reproduce the result. How can i convert the lab files after the command? Thanks in advance.

Here's the one from colab

> 0 50000 x^x-sil+hh=iy@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:1+1+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_1/G:0_0/H:x=x@1=2|0/I:4=3/J:13+9-2[2]
50000 100000 x^x-sil+hh=iy@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:1+1+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_1/G:0_0/H:x=x@1=2|0/I:4=3/J:13+9-2[3]
100000 1200000 x^x-sil+hh=iy@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:1+1+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_1/G:0_0/H:x=x@1=2|0/I:4=3/J:13+9-2[4]
1200000 1250000 x^x-sil+hh=iy@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:1+1+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_1/G:0_0/H:x=x@1=2|0/I:4=3/J:13+9-2[5]
1250000 1300000 x^x-sil+hh=iy@x_x/A:0_0_0/B:x-x-x@x-x&x-x#x-x$x-x!x-x;x-x|x/C:1+1+2/D:0_0/E:x+x@x+x&x+x#x+x/F:content_1/G:0_0/H:x=x@1=2|0/I:4=3/J:13+9-2[6]
1300000 1600000 x^sil-hh+iy=t@1_2/A:0_0_0/B:1-1-2@1-1&1-4#1-3$1-4!0-1;0-1|iy/C:1+1+4/D:0_0/E:content+1@1+3&1+2#0+1/F:content_1/G:0_0/H:4=3@1=2|L-H%/I:9=6/J:13+9-2[2]

but what I've got is

> 0.0000000 0.3125000 silB
0.3125000 0.3525000 m
0.3525000 0.4325000 i
0.4325000 0.5225000 z
0.5225000 0.5525000 u
0.5525000 0.6525000 o
0.6525000 0.7525000 m
0.7525000 0.8225000 a
0.8225000 0.8725000 r
0.8725000 0.9725000 e:
0.9725000 1.0925000 sh
1.0925000 1.1225000 i
1.1225000 1.2325000 a

**Comment by r9y9** [comment]
Hi, thanks for using this! Here goes the label files: https://github.com/r9y9/jsut-lab. There's code to reproduce the label files https://github.com/r9y9/segmentation-kit/tree/jsut2 (disclaimer: no docs for this. If you are interested, see run.sh and [a-d].py). I hope it helps!

**Comment by thrfdth** [comment]
Thanks for your reply. Would it be possible to convert the lab files from jsut2 to the ones from jsut-lab?
After running the run.sh (including d.py) in jsut2 repo , i still got pretty much the same lab files (not full-context label? I'm not sure the name). which are written in different time unit.

what i assumed is somthing like this:

> 0 3125000 xx^xx-sil+m=i/A:xx+xx+xx/B:xx-xx_xx/C:xx_xx+xx/D:02+xx_xx/E:xx_xx!xx_xx-xx/F:xx_xx#xx_xx@xx_xx|xx_xx/G:3_3%0_xx_xx/H:xx_xx/I:xx-xx@xx+xx&xx-xx|xx+xx/J:5_23/K:1+5-23
3125000 3525000 xx^sil-m+i=z/A:-2+1+3/B:xx-xx_xx/C:02_xx+xx/D:13+xx_xx/E:xx_xx!xx_xx-xx/F:3_3#0_xx@1_5|1_23/G:7_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
3525000 4325000 sil^m-i+z=u/A:-2+1+3/B:xx-xx_xx/C:02_xx+xx/D:13+xx_xx/E:xx_xx!xx_xx-xx/F:3_3#0_xx@1_5|1_23/G:7_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
4325000 5225000 m^i-z+u=o/A:-1+2+2/B:xx-xx_xx/C:02_xx+xx/D:13+xx_xx/E:xx_xx!xx_xx-xx/F:3_3#0_xx@1_5|1_23/G:7_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
5225000 5525000 i^z-u+o=m/A:-1+2+2/B:xx-xx_xx/C:02_xx+xx/D:13+xx_xx/E:xx_xx!xx_xx-xx/F:3_3#0_xx@1_5|1_23/G:7_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
5525000 6525000 z^u-o+m=a/A:0+3+1/B:02-xx_xx/C:13_xx+xx/D:18+xx_xx/E:xx_xx!xx_xx-xx/F:3_3#0_xx@1_5|1_23/G:7_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
6525000 7524999 u^o-m+a=r/A:-1+1+7/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
7524999 8225000 o^m-a+r=e/A:-1+1+7/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
8225000 8725000 m^a-r+e=e/A:0+2+6/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
8725000 9125000 a^r-e+e=sh/A:0+2+6/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
9125000 9725000 r^e-e+sh=i/A:1+3+5/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
9725000 10925000 e^e-sh+i=a/A:2+4+4/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
10925000 11225000 e^sh-i+a=k/A:2+4+4/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
11225000 12325000 sh^i-a+k=a/A:3+5+3/B:13-xx_xx/C:18_xx+xx/D:13+xx_xx/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
12325000 12925000 i^a-k+a=r/A:4+6+2/B:18-xx_xx/C:13_xx+xx/D:20+1_0/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
12925000 13325000 a^k-a+r=a/A:4+6+2/B:18-xx_xx/C:13_xx+xx/D:20+1_0/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
13325000 13825000 k^a-r+a=k/A:5+7+1/B:18-xx_xx/C:13_xx+xx/D:20+1_0/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
13825000 14325000 a^r-a+k=a/A:5+7+1/B:18-xx_xx/C:13_xx+xx/D:20+1_0/E:3_3!0_xx-1/F:7_2#0_xx@2_4|4_20/G:6_6%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
14325000 15325000 r^a-k+a=w/A:-5+1+6/B:13-xx_xx/C:20_1+0/D:10+7_1/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
15325000 15925000 a^k-a+w=a/A:-5+1+6/B:13-xx_xx/C:20_1+0/D:10+7_1/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
15925000 16825000 k^a-w+a=n/A:-4+2+5/B:13-xx_xx/C:20_1+0/D:10+7_1/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
16825000 17225000 a^w-a+n=a/A:-4+2+5/B:13-xx_xx/C:20_1+0/D:10+7_1/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
17225000 17725000 w^a-n+a=k/A:-3+3+4/B:20-1_0/C:10_7+1/D:12+xx_xx/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
17725000 18425000 a^n-a+k=U/A:-3+3+4/B:20-1_0/C:10_7+1/D:12+xx_xx/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
18425000 18925000 n^a-k+U=t/A:-2+4+3/B:20-1_0/C:10_7+1/D:12+xx_xx/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
18925000 19225000 a^k-U+t=e/A:-2+4+3/B:20-1_0/C:10_7+1/D:12+xx_xx/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
19225000 19725000 k^U-t+e=w/A:-1+5+2/B:10-7_1/C:12_xx+xx/D:24+xx_xx/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
19725000 20025000 U^t-e+w=a/A:-1+5+2/B:10-7_1/C:12_xx+xx/D:24+xx_xx/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
20025000 20724999 t^e-w+a=n/A:0+6+1/B:12-xx_xx/C:24_xx+xx/D:17+1_0/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
20724999 21125000 e^w-a+n=a/A:0+6+1/B:12-xx_xx/C:24_xx+xx/D:17+1_0/E:7_2!0_xx-1/F:6_6#0_xx@3_3|11_13/G:4_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
21125000 21825000 w^a-n+a=r/A:-1+1+4/B:24-xx_xx/C:17_1+0/D:10+7_2/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
21825000 22525000 a^n-a+r=a/A:-1+1+4/B:24-xx_xx/C:17_1+0/D:10+7_2/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
22525000 23025000 n^a-r+a=n/A:0+2+3/B:24-xx_xx/C:17_1+0/D:10+7_2/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
23025000 23424999 a^r-a+n=a/A:0+2+3/B:24-xx_xx/C:17_1+0/D:10+7_2/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
23424999 24225000 r^a-n+a=i/A:1+3+2/B:17-1_0/C:10_7+2/D:22+xx_xx/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
24225000 24725000 a^n-a+i=n/A:1+3+2/B:17-1_0/C:10_7+2/D:22+xx_xx/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
24725000 25025000 n^a-i+n=o/A:2+4+1/B:17-1_0/C:10_7+2/D:22+xx_xx/E:6_6!0_xx-1/F:4_2#0_xx@4_2|17_7/G:3_2%0_xx_1/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
25025000 25724999 a^i-n+o=d/A:-1+1+3/B:10-7_2/C:22_xx+xx/D:10+7_2/E:4_2!0_xx-1/F:3_2#0_xx@5_1|21_3/G:xx_xx%xx_xx_xx/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
25724999 26125000 i^n-o+d=e/A:-1+1+3/B:10-7_2/C:22_xx+xx/D:10+7_2/E:4_2!0_xx-1/F:3_2#0_xx@5_1|21_3/G:xx_xx%xx_xx_xx/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
26125000 26525000 n^o-d+e=s/A:0+2+2/B:22-xx_xx/C:10_7+2/D:xx+xx_xx/E:4_2!0_xx-1/F:3_2#0_xx@5_1|21_3/G:xx_xx%xx_xx_xx/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
26525000 27325000 o^d-e+s=U/A:0+2+2/B:22-xx_xx/C:10_7+2/D:xx+xx_xx/E:4_2!0_xx-1/F:3_2#0_xx@5_1|21_3/G:xx_xx%xx_xx_xx/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
27325000 29625000 d^e-s+U=sil/A:1+3+1/B:22-xx_xx/C:10_7+2/D:xx+xx_xx/E:4_2!0_xx-1/F:3_2#0_xx@5_1|21_3/G:xx_xx%xx_xx_xx/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
29625000 30025000 e^s-U+sil=xx/A:1+3+1/B:22-xx_xx/C:10_7+2/D:xx+xx_xx/E:4_2!0_xx-1/F:3_2#0_xx@5_1|21_3/G:xx_xx%xx_xx_xx/H:xx_xx/I:5-23@1+1&1-5|1+23/J:xx_xx/K:1+5-23
30025000 31825000 s^U-sil+xx=xx/A:xx+xx+xx/B:10-7_2/C:xx_xx+xx/D:xx+xx_xx/E:3_2!0_xx-xx/F:xx_xx#xx_xx@xx_xx|xx_xx/G:xx_xx%xx_xx_xx/H:5_23/I:xx-xx@xx+xx&xx-xx|xx+xx/J:xx_xx/K:1+5-23

not like this: 

> 0 3125000 silB
3125000 3525000 m
3525000 4325000 i
4325000 5225000 z
5225000 5525000 u
5525000 6525000 o
6525000 7524999 m
7524999 8225000 a
8225000 8725000 r
8725000 9725000 e:
9725000 10925000 sh
10925000 11225000 i
11225000 12325000 a
12325000 12925000 k
12925000 13325000 a
13325000 13825000 r
13825000 14325000 a
14325000 15325000 k
15325000 15925000 a
15925000 16825000 w
16825000 17225000 a
17225000 17725000 n
17725000 18425000 a
18425000 19025000 k
19025000 19325000 u
19325000 19725000 t
19725000 20025000 e
20025000 20325000 h
20325000 21125000 a
21125000 21825000 n
21825000 22525000 a
22525000 23025000 r
23025000 23424999 a
23424999 24225000 n
24225000 24725000 a
24725000 25025000 i
25025000 25724999 n
25724999 26125000 o
26125000 26525000 d
26525000 27325000 e
27325000 29625000 s
29625000 30025000 u
30025000 31825000 silE

**Comment by r9y9** [comment]
Please make sure that you are on the right branch (jsut2, not jsut). Full-context labels (w/o time alignment) are generated by a.py using the [OpenJTalk frontend](https://github.com/r9y9/pyopenjtalk). See https://github.com/r9y9/segmentation-kit/blob/8baff2caa6d15fc52c53e9b37e765466c106c02a/a.py#L34-L61

The final outputs, time-aligned full-context labels, are obtained by combining the time alignment (which you showed) and the full-context labels (w/o time alignment). See https://github.com/r9y9/segmentation-kit/blob/8baff2caa6d15fc52c53e9b37e765466c106c02a/d.py#L12-L26 for the code.

**Comment by thrfdth** [comment]
I was using the wrong jsut branch! Thanks you saved me!

**Comment by r9y9** [comment]
You are welcome :)
