### ISSUE TITLE
Future warning from sklearn

### ISSUE THREAD

**Issue by auspicious3000** [r9y9/nnmnkwii#99]
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)

This of course does not affect the functionality of the package, but it would be optimal to fix it before it is too late. 

Thank you very much!

**Comment by r9y9** [comment]
Could you show which part of nnmnkwii causes the warning?

**Comment by auspicious3000** [comment]
@r9y9 It shows when I execute **from nnmnkwii import preprocessing as P**.   It also shows when training your wavenet_vocoder.

**Comment by r9y9** [comment]
Thanks! This should be fixed by #100.

**Comment by auspicious3000** [comment]
@r9y9 Thanks for your fast response! If I install nnmnkwii using pip, how soon will the fix be reflected?

**Comment by r9y9** [comment]
Could you install nnmnkwii by the following command? 

```
pip install git+https://github.com/r9y9/nnmnkwii
```

This should install the latest development version of nnmnkwii.

**Comment by r9y9** [comment]
The fix is landed on the latest release (v0.0.21), so we can install it with just `pip install nnmnkwii`. Sorry for the inconvenience again!
